function mkTask(t) {
  return {
    taskNumber: t.taskNumber,
    title: t.title,
    description: t.description,
    instructions: t.instructions,
    submissionType: t.submissionType,
    dueInDays: t.dueInDays,
    points: 20,
  };
}

const webDevTasks = [
  mkTask({
    taskNumber: 1,
    title: "Personal Portfolio Website",
    description: "Build a responsive personal portfolio showcasing your skills, projects, and contact details.",
    instructions: "Build a clean, responsive personal portfolio site (HTML, CSS, JavaScript). Include at least 4 sections — Hero, About, Projects, Contact — and a working contact form. Deploy to GitHub Pages or Netlify. Submit GitHub Repository Link, Live Website URL, and a Project Report PDF.",
    submissionType: "github",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 2,
    title: "Restaurant Website",
    description: "Design and develop a modern restaurant website with menu, gallery, and reservation form.",
    instructions: "Build a static/dynamic restaurant website (HTML, CSS, JS, optionally a small framework). Include menu sections, image gallery, location map, and a reservation form. Make it fully responsive. Submit GitHub Repository Link, Live Website URL, and a Project Report PDF.",
    submissionType: "github",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 3,
    title: "E-Commerce Landing Page",
    description: "Create a high-conversion e-commerce landing page with product showcase and CTA.",
    instructions: "Design and build a single-page e-commerce landing page with hero banner, product showcase grid, features, testimonials, and a strong CTA. Responsive and optimized for performance. Submit GitHub Repository Link, Live Website URL, and a Project Report PDF.",
    submissionType: "github",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 4,
    title: "College Event Website",
    description: "Build a website for a college event with schedule, speakers, sponsors, and registration.",
    instructions: "Create an event website with sections for About, Schedule, Speakers, Sponsors, and a Registration form. Use semantic HTML, accessible markup, and a consistent theme. Submit GitHub Repository Link, Live Website URL, and a Project Report PDF.",
    submissionType: "github",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 5,
    title: "Company Business Website",
    description: "Develop a multi-section corporate business website with services, team, and contact.",
    instructions: "Build a multi-page corporate website with Home, Services, About/Team, Portfolio, and Contact pages. Ensure consistent design across pages, SEO-friendly metadata, and contact form with validation. Submit GitHub Repository Link, Live Website URL, and a Project Report PDF.",
    submissionType: "github",
    dueInDays: 14,
  }),
];

const fullStackTasks = [
  mkTask({
    taskNumber: 1,
    title: "Student Management System",
    description: "Build a CRUD-based system to manage students, courses, and enrollments.",
    instructions: "Implement a Student Management System with full CRUD for students and courses. Use a frontend framework, REST API, and a database. Include login, validation, and proper error states. Submit GitHub Repository, Live Project URL, and Documentation PDF.",
    submissionType: "github",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 2,
    title: "Task Management Application",
    description: "Develop a multi-user task manager with boards/lists, priorities, and due dates.",
    instructions: "Build a Task Management app with user authentication, multiple boards or lists, drag-and-drop task movement, priorities, and due dates. Persist data in a database. Submit GitHub Repository, Live Project URL, and Documentation PDF.",
    submissionType: "github",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 3,
    title: "Employee Management System",
    description: "Create an HR system for employees, departments, attendance, and payroll basics.",
    instructions: "Build an Employee Management System with modules for employee records, departments, attendance tracking, and basic payroll calculations. Include role-based access (admin/HR). Submit GitHub Repository, Live Project URL, and Documentation PDF.",
    submissionType: "github",
    dueInDays: 14,
  }),
  mkTask({
    taskNumber: 4,
    title: "Online Course Platform",
    description: "Build an LMS-style platform with courses, lessons, video playback, and progress.",
    instructions: "Develop an online course platform with course catalog, lesson pages with video, progress tracking, and a simple quiz. Use a real database. Submit GitHub Repository, Live Project URL, and Documentation PDF.",
    submissionType: "github",
    dueInDays: 14,
  }),
  mkTask({
    taskNumber: 5,
    title: "E-Commerce Web Application",
    description: "Build a full-stack e-commerce app with product catalog, cart, checkout, and admin.",
    instructions: "Implement a complete e-commerce web application: product catalog, search, product details, cart, checkout (mock payment OK), user accounts, and an admin panel for product management. Submit GitHub Repository, Live Project URL, and Documentation PDF.",
    submissionType: "github",
    dueInDays: 14,
  }),
];

const mernTasks = [
  mkTask({
    taskNumber: 1,
    title: "Task Manager App",
    description: "Build a MERN task manager with authentication and persistent storage.",
    instructions: "Use MongoDB, Express, React, and Node.js. Build a task manager with user auth, CRUD tasks, status updates, and due dates. Deploy the front-end (Vercel/Netlify) and back-end (Render/Railway). Submit GitHub Link, Deployment Link, and a Demo Video.",
    submissionType: "github",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 2,
    title: "Expense Tracker",
    description: "Create a MERN expense tracker with categories, charts, and monthly summaries.",
    instructions: "Build an expense tracker with MERN. Include add/edit/delete expenses, categories, monthly and category charts (Recharts/Chart.js), and JWT auth. Submit GitHub Link, Deployment Link, and a Demo Video.",
    submissionType: "github",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 3,
    title: "Job Portal",
    description: "Build a MERN job board with employer and job-seeker roles, listings, and applications.",
    instructions: "Implement a job portal with employer and job-seeker roles, job postings, search/filter, and application flow. Use MERN stack with proper authorization. Submit GitHub Link, Deployment Link, and a Demo Video.",
    submissionType: "github",
    dueInDays: 14,
  }),
  mkTask({
    taskNumber: 4,
    title: "Online Learning Platform",
    description: "Build a MERN learning platform with courses, lessons, and progress tracking.",
    instructions: "Develop a learning platform with course catalog, lesson pages with video, enrollment, and progress tracking. Use MERN with protected routes. Submit GitHub Link, Deployment Link, and a Demo Video.",
    submissionType: "github",
    dueInDays: 14,
  }),
  mkTask({
    taskNumber: 5,
    title: "E-Commerce MERN Store",
    description: "Build a MERN e-commerce store with cart, checkout, and admin product management.",
    instructions: "Build a MERN e-commerce store: product catalog, search, product details, cart, checkout (mock payment), and an admin panel for product CRUD. Deploy front and back end. Submit GitHub Link, Deployment Link, and a Demo Video.",
    submissionType: "github",
    dueInDays: 14,
  }),
];

const uiuxTasks = [
  mkTask({
    taskNumber: 1,
    title: "Food Delivery App UI",
    description: "Design a complete UI for a food delivery app — onboarding, home, menu, cart, tracking.",
    instructions: "Design a full mobile flow for a food delivery app in Figma: Splash, Onboarding, Home, Restaurant list, Menu, Cart, Order tracking, and Profile. Use a clean design system with components, colors, and typography. Submit Figma Link, Prototype Link, and a PDF Design File.",
    submissionType: "link",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 2,
    title: "E-Commerce App UI",
    description: "Design a mobile e-commerce app UI with product browse, search, and checkout flow.",
    instructions: "Design a mobile e-commerce app in Figma: Home, Categories, Search, Product details, Cart, Checkout, and Order confirmation. Include reusable components and a style guide. Submit Figma Link, Prototype Link, and a PDF Design File.",
    submissionType: "link",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 3,
    title: "Banking App UI",
    description: "Design a mobile banking app UI with dashboard, transfer, and statements.",
    instructions: "Design a banking app UI in Figma: Login (biometric mock), Dashboard, Accounts, Transfer flow, Cards, Statements, and Profile. Apply proper information hierarchy and accessibility. Submit Figma Link, Prototype Link, and a PDF Design File.",
    submissionType: "link",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 4,
    title: "Travel Booking Website UI",
    description: "Design a travel booking website with search, listings, booking flow, and user dashboard.",
    instructions: "Design a desktop + mobile travel booking site in Figma: Home, Search, Listings, Details, Booking flow, My Trips, and Profile. Include responsive variants. Submit Figma Link, Prototype Link, and a PDF Design File.",
    submissionType: "link",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 5,
    title: "Company Dashboard Design",
    description: "Design a SaaS company dashboard with analytics, sidebar nav, and key widgets.",
    instructions: "Design an admin/company dashboard in Figma: Sidebar, Top bar, KPIs, Charts, Tables, and a Reports page. Use a consistent design system and dark/light variants. Submit Figma Link, Prototype Link, and a PDF Design File.",
    submissionType: "link",
    dueInDays: 14,
  }),
];

const digitalMarketingTasks = [
  mkTask({
    taskNumber: 1,
    title: "Social Media Campaign",
    description: "Plan and design a multi-platform social media campaign for a brand or product.",
    instructions: "Choose a brand or product. Plan a 2-week social media campaign with platform mix (Instagram, LinkedIn, X), content calendar, copy, and visual direction. Submit a Canva Link, a Campaign Report PDF, and Analytics Screenshots (mock or real).",
    submissionType: "link",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 2,
    title: "Instagram Growth Strategy",
    description: "Develop an Instagram growth plan with content pillars, posting schedule, and metrics.",
    instructions: "Pick a niche account. Develop a 30-day Instagram growth strategy: content pillars, posting schedule, hashtag research, engagement plan, and KPI targets. Submit a Canva Link, a Campaign Report PDF, and Analytics Screenshots.",
    submissionType: "link",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 3,
    title: "Facebook Ad Campaign Plan",
    description: "Plan a Facebook ad campaign with audience, creatives, copy, and budget split.",
    instructions: "Build a Facebook (Meta) Ads campaign plan: objective, audience targeting, ad creatives (3+), ad copy variations, budget split, and KPI plan. Submit a Canva Link, a Campaign Report PDF, and Analytics Screenshots.",
    submissionType: "link",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 4,
    title: "Brand Promotion Campaign",
    description: "Create a 360-degree brand promotion campaign with messaging and creative assets.",
    instructions: "Develop a 360-degree brand promotion plan: positioning, key messages, channel mix, creative brief, and 5+ asset mockups (social posts, banner, email). Submit a Canva Link, a Campaign Report PDF, and Analytics Screenshots.",
    submissionType: "link",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 5,
    title: "Lead Generation Project",
    description: "Build a lead generation funnel with a landing page, ad creative, and conversion plan.",
    instructions: "Design and prototype a lead generation funnel: lead magnet, landing page (Figma/HTML), ad creative, email sequence, and a dashboard mock for tracking. Submit a Canva Link, a Campaign Report PDF, and Analytics Screenshots.",
    submissionType: "link",
    dueInDays: 14,
  }),
];

const seoTasks = [
  mkTask({
    taskNumber: 1,
    title: "Website SEO Audit",
    description: "Run a full SEO audit on a chosen website and document issues and recommendations.",
    instructions: "Pick any public website. Run a technical, on-page, and basic off-page SEO audit using free tools (Lighthouse, Screaming Frog free, PageSpeed Insights). Document issues, severity, and recommendations. Submit an SEO Audit PDF, a Keyword Research Sheet, and Screenshots.",
    submissionType: "file",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 2,
    title: "Keyword Research Project",
    description: "Build a keyword research sheet for a chosen topic or business with intent and difficulty.",
    instructions: "Choose a topic or business. Build a keyword research sheet (Excel/Sheets) of 30+ keywords grouped by intent, with monthly volume, difficulty, and priority. Submit an SEO Audit PDF, a Keyword Research Sheet, and Screenshots.",
    submissionType: "file",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 3,
    title: "On-Page SEO Optimization",
    description: "Optimize a real or demo page for on-page SEO: titles, meta, headings, schema, internal links.",
    instructions: "Take a real or demo page. Optimize title tag, meta description, H1-H6, image alt text, internal links, and add JSON-LD schema where relevant. Document changes and impact. Submit an SEO Audit PDF, a Keyword Research Sheet, and Screenshots.",
    submissionType: "file",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 4,
    title: "Competitor Analysis",
    description: "Analyze 3-5 competitors for content, keywords, backlinks, and positioning.",
    instructions: "Pick a niche and 3-5 competitors. Analyze their top pages, target keywords, content gaps, backlink profile (free tools), and positioning. Submit an SEO Audit PDF, a Keyword Research Sheet, and Screenshots.",
    submissionType: "file",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 5,
    title: "SEO Performance Report",
    description: "Compile a 4-week SEO performance report with traffic, rankings, and recommendations.",
    instructions: "Build a 4-week SEO performance report (own site or a demo one) with traffic trends, ranking changes, content output, and 5 prioritized next steps. Submit an SEO Audit PDF, a Keyword Research Sheet, and Screenshots.",
    submissionType: "file",
    dueInDays: 14,
  }),
];

const graphicDesignTasks = [
  mkTask({
    taskNumber: 1,
    title: "Company Logo Design",
    description: "Design a clean, memorable company logo with monochrome and color variations.",
    instructions: "Design a company logo in vector (Figma/Illustrator). Deliver the primary mark, monogram, monochrome versions, color palette, and a brief rationale. Submit PNG/JPG Files, Source Files, and a Portfolio PDF.",
    submissionType: "file",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 2,
    title: "Social Media Poster Pack",
    description: "Create a pack of 6+ social media posters with consistent visual style.",
    instructions: "Design a pack of 6+ social media posters (Instagram/Facebook sizes) with a consistent visual style for a chosen brand/event. Include captions and hashtags. Submit PNG/JPG Files, Source Files, and a Portfolio PDF.",
    submissionType: "file",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 3,
    title: "Business Brochure Design",
    description: "Design a tri-fold or bi-fold business brochure (print-ready + digital).",
    instructions: "Design a business brochure (tri-fold or bi-fold) in print-ready PDF (CMYK, 3mm bleed) and a digital share version. Include cover, services, and contact. Submit PNG/JPG Files, Source Files, and a Portfolio PDF.",
    submissionType: "file",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 4,
    title: "Event Banner Design",
    description: "Design event banners — web header, social cover, and standee/poster variants.",
    instructions: "Design an event banner set: web header (1500x500), social cover (820x312), and a poster (A3/A2). Maintain a consistent visual theme. Submit PNG/JPG Files, Source Files, and a Portfolio PDF.",
    submissionType: "file",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 5,
    title: "Complete Brand Identity Kit",
    description: "Design a complete brand identity kit: logo, colors, typography, stationery, social templates.",
    instructions: "Build a complete brand identity kit for a fictional or real brand: logo system, color palette, typography, business card, letterhead, social media templates, and brand guidelines PDF. Submit PNG/JPG Files, Source Files, and a Portfolio PDF.",
    submissionType: "file",
    dueInDays: 14,
  }),
];

const contentWritingTasks = [
  mkTask({
    taskNumber: 1,
    title: "Write 5 SEO Blogs",
    description: "Write 5 SEO-optimized blog posts on a chosen niche with proper structure and keywords.",
    instructions: "Pick a niche. Write 5 SEO-friendly blog posts (800-1200 words each) with target keyword, meta description, internal links, and a featured image suggestion. Submit a Google Docs Link, a PDF Portfolio, and Published URLs.",
    submissionType: "link",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 2,
    title: "Company Website Content",
    description: "Write complete website content: home, about, services, and contact pages.",
    instructions: "Write full website copy for a chosen brand: Home (hero, sub-hero, features), About, Services (3-5), Testimonials, FAQ, and Contact. Keep tone consistent and SEO-aware. Submit a Google Docs Link, a PDF Portfolio, and Published URLs.",
    submissionType: "link",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 3,
    title: "Product Descriptions",
    description: "Write compelling product descriptions for 10+ e-commerce products.",
    instructions: "Pick a product category. Write product descriptions for 10+ products — headline, 3-4 benefit bullets, 150-200 word description, and meta title/description. Submit a Google Docs Link, a PDF Portfolio, and Published URLs.",
    submissionType: "link",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 4,
    title: "Social Media Content Calendar",
    description: "Build a 30-day social media content calendar with captions and hashtags.",
    instructions: "Create a 30-day social media content calendar for a chosen brand. Include post type, caption, hashtags, and visual direction for each day. Submit a Google Docs Link, a PDF Portfolio, and Published URLs.",
    submissionType: "link",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 5,
    title: "Content Portfolio Creation",
    description: "Compile all your written work into a polished content writing portfolio.",
    instructions: "Compile a content writing portfolio PDF that includes your best pieces (blogs, website copy, product descriptions, social content) with a brief intro and table of contents. Share a Google Docs Link, a PDF Portfolio, and Published URLs.",
    submissionType: "link",
    dueInDays: 14,
  }),
];

const ecommerceMgmtTasks = [
  mkTask({
    taskNumber: 1,
    title: "Product Listing Project",
    description: "List 20+ products on an e-commerce platform with full details and SEO.",
    instructions: "On any e-commerce platform (Amazon/Flipkart/Shopify demo), create 20+ optimized product listings — title, 5+ images, bullet points, description, and backend keywords. Submit an Excel File, a Report PDF, and Screenshots.",
    submissionType: "file",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 2,
    title: "Product Optimization",
    description: "Optimize existing product listings — titles, images, descriptions, A+ content.",
    instructions: "Take 10 existing product listings and optimize them: rewrite titles, improve descriptions, add A+/rich content, and improve image quality. Document before/after. Submit an Excel File, a Report PDF, and Screenshots.",
    submissionType: "file",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 3,
    title: "Inventory Tracking Sheet",
    description: "Build an inventory tracking sheet with stock levels, reorder points, and SKUs.",
    instructions: "Create an inventory tracking sheet (Excel/Sheets) with SKU, product name, category, stock on hand, reorder point, supplier, and lead time. Add a simple dashboard for low-stock alerts. Submit an Excel File, a Report PDF, and Screenshots.",
    submissionType: "file",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 4,
    title: "Sales Analysis Report",
    description: "Analyze a sales dataset and produce a report with insights and recommendations.",
    instructions: "Using a sample sales dataset, analyze revenue, top products, seasonality, and return rate. Produce a written report with charts and 3-5 actionable insights. Submit an Excel File, a Report PDF, and Screenshots.",
    submissionType: "file",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 5,
    title: "Online Store Management",
    description: "Run a small online store for 2 weeks — listings, orders, support, and reporting.",
    instructions: "Set up and run a small online store (Shopify free trial, WooCommerce, or Etsy) for 2 weeks. Add at least 10 products, process at least 3 mock orders, and produce a final report. Submit an Excel File, a Report PDF, and Screenshots.",
    submissionType: "file",
    dueInDays: 14,
  }),
];

const aiPromptTasks = [
  mkTask({
    taskNumber: 1,
    title: "AI Prompt Library",
    description: "Build a categorized AI prompt library with 30+ tested prompts.",
    instructions: "Curate a prompt library (Notion/Google Doc) of 30+ tested prompts across categories like writing, coding, design, research, and productivity. For each prompt include goal, model used, and example output. Submit a Prompt PDF, Screenshots, and a Final Report.",
    submissionType: "file",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 2,
    title: "AI Content Generator Workflow",
    description: "Design a content generation workflow using AI tools (text + image).",
    instructions: "Design an end-to-end content generator workflow: idea prompt → outline prompt → draft prompt → image prompt → formatting. Test it for one content type (e.g., blog + cover image). Submit a Prompt PDF, Screenshots, and a Final Report.",
    submissionType: "file",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 3,
    title: "Customer Support Chatbot Prompts",
    description: "Build a customer support chatbot prompt set with intent, fallback, and tone rules.",
    instructions: "Design a customer support chatbot prompt set: greeting, FAQ intent handlers, refund/return flows, escalation rule, and a friendly tone guardrail. Simulate 5 sample conversations. Submit a Prompt PDF, Screenshots, and a Final Report.",
    submissionType: "file",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 4,
    title: "AI Marketing Automation",
    description: "Plan an AI-driven marketing automation flow with prompts and tools.",
    instructions: "Design a marketing automation flow using AI: lead scoring prompt, email subject generator, social copy generator, and a weekly analytics digest prompt. Include sample outputs. Submit a Prompt PDF, Screenshots, and a Final Report.",
    submissionType: "file",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 5,
    title: "AI Business Solution Project",
    description: "Identify a real business problem and build an AI-based solution using prompt engineering.",
    instructions: "Identify a real business problem (any small business). Design and prototype an AI-based solution using prompt engineering and (optionally) no-code tools. Document the problem, solution, prompts, and outcomes. Submit a Prompt PDF, Screenshots, and a Final Report.",
    submissionType: "file",
    dueInDays: 14,
  }),
];

const reactTasks = [
  mkTask({
    taskNumber: 1,
    title: "Weather Application",
    description: "Build a React weather app using a public weather API.",
    instructions: "Build a React weather app (Vite or CRA). Use a free weather API (Open-Meteo or OpenWeather). Show current weather, 5-day forecast, search by city, and loading/error states. Deploy to Vercel/Netlify. Submit GitHub Link, Live URL, and Documentation.",
    submissionType: "github",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 2,
    title: "Movie Search Application",
    description: "Build a React movie search app using the OMDB or TMDB API.",
    instructions: "Build a React movie search app using TMDB or OMDB API. Include search, results grid, detail view, and favorites (localStorage). Deploy to Vercel/Netlify. Submit GitHub Link, Live URL, and Documentation.",
    submissionType: "github",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 3,
    title: "Expense Tracker",
    description: "Create a React expense tracker with charts and category breakdowns.",
    instructions: "Build a React expense tracker with add/edit/delete transactions, categories, monthly and category charts (Recharts/Chart.js), and localStorage persistence. Deploy. Submit GitHub Link, Live URL, and Documentation.",
    submissionType: "github",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 4,
    title: "Admin Dashboard",
    description: "Build a React admin dashboard with charts, tables, and a sidebar layout.",
    instructions: "Build a React admin dashboard (Vite + Tailwind) with sidebar navigation, top bar, KPIs, charts, and a data table (sorting, filtering, pagination). Use mock JSON or a public API. Deploy. Submit GitHub Link, Live URL, and Documentation.",
    submissionType: "github",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 5,
    title: "React E-Commerce Website",
    description: "Build a React e-commerce storefront with cart and product detail pages.",
    instructions: "Build a React e-commerce storefront: home, product list, product detail, cart, and checkout (mock). Use Context or Redux for cart state. Deploy. Submit GitHub Link, Live URL, and Documentation.",
    submissionType: "github",
    dueInDays: 14,
  }),
];

const dataAnalyticsTasks = [
  mkTask({
    taskNumber: 1,
    title: "Sales Dashboard",
    description: "Build a sales dashboard with KPIs, trends, and product breakdowns.",
    instructions: "Using a sample sales dataset, build a sales dashboard in Excel or Power BI with KPIs (revenue, orders, AOV), trend lines, top products, and region filters. Submit an Excel/Power BI File, a PDF Report, and a Presentation.",
    submissionType: "file",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 2,
    title: "Customer Analysis Report",
    description: "Analyze customer behavior, segments, and lifetime value.",
    instructions: "Analyze a customer dataset: demographics, purchase behavior, segments, and basic CLV. Produce a written report with charts and 3-5 business recommendations. Submit an Excel/Power BI File, a PDF Report, and a Presentation.",
    submissionType: "file",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 3,
    title: "Market Trend Analysis",
    description: "Research and analyze a market trend using public data and visualizations.",
    instructions: "Choose a market (e.g., EVs, edtech, fintech). Use public data to analyze 3-5 year trends, drivers, and forecasts. Produce a slide deck and a written report. Submit an Excel/Power BI File, a PDF Report, and a Presentation.",
    submissionType: "file",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 4,
    title: "Data Visualization Project",
    description: "Build a data story with 5+ interactive visualizations.",
    instructions: "Choose a topic. Build a data visualization project with at least 5 interactive charts (Tableau Public, Power BI, or D3.js). Include a write-up of insights. Submit an Excel/Power BI File, a PDF Report, and a Presentation.",
    submissionType: "file",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 5,
    title: "Business Insights Dashboard",
    description: "Build an executive business insights dashboard with KPIs and narratives.",
    instructions: "Build an executive business insights dashboard: revenue, costs, profit, customer acquisition, retention, and a forecasting sheet. Include a written executive summary. Submit an Excel/Power BI File, a PDF Report, and a Presentation.",
    submissionType: "file",
    dueInDays: 14,
  }),
];

const videoEditingTasks = [
  mkTask({
    taskNumber: 1,
    title: "Instagram Reel Editing",
    description: "Edit a 15-30 second Instagram reel with transitions, captions, and music.",
    instructions: "Edit a 15-30 second Instagram reel: hook, cuts on beat, captions, transitions, color correction, and royalty-free music. Export in 9:16 1080x1920. Submit an MP4 File, a Drive Link, and a Thumbnail Design.",
    submissionType: "file",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 2,
    title: "YouTube Video Editing",
    description: "Edit a 3-5 minute YouTube video with intro, B-roll, captions, and lower thirds.",
    instructions: "Edit a 3-5 minute YouTube video: intro, B-roll, lower thirds, captions, transitions, sound design, and color grade. Export 16:9 1080p or 4K. Submit an MP4 File, a Drive Link, and a Thumbnail Design.",
    submissionType: "file",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 3,
    title: "Promotional Video Creation",
    description: "Create a 30-60 second brand/product promotional video.",
    instructions: "Produce a 30-60 second promotional video for a product or service: script, storyboard, footage, motion graphics, music, and final edit. Export 16:9 and 9:16. Submit an MP4 File, a Drive Link, and a Thumbnail Design.",
    submissionType: "file",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 4,
    title: "Motion Graphics Video",
    description: "Create a 20-40 second motion graphics video with text animations and shapes.",
    instructions: "Create a 20-40 second motion graphics video (After Effects or similar) with kinetic typography, animated shapes, smooth transitions, and a sound design layer. Submit an MP4 File, a Drive Link, and a Thumbnail Design.",
    submissionType: "file",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 5,
    title: "Brand Advertisement Video",
    description: "Edit a 30-60 second brand advertisement with story, sound, and color.",
    instructions: "Edit a 30-60 second brand advertisement: concept, storyboard, footage, color grading, sound design, and final output. Export in 16:9 and 9:16. Submit an MP4 File, a Drive Link, and a Thumbnail Design.",
    submissionType: "file",
    dueInDays: 14,
  }),
];

const softwareTestingTasks = [
  mkTask({
    taskNumber: 1,
    title: "Website Testing Report",
    description: "Test a public website and document functional, UI, and basic performance issues.",
    instructions: "Test a public website (e.g., an e-commerce site). Document functional bugs, UI/UX issues, and basic performance (PageSpeed). Write clear test cases and bug reports. Submit Test Cases PDF, Bug Report, and Screenshots.",
    submissionType: "file",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 2,
    title: "Mobile App Testing",
    description: "Test a mobile app and document functional and usability issues.",
    instructions: "Install a public mobile app. Test core flows, document functional and usability bugs, and run basic compatibility checks across device profiles. Submit Test Cases PDF, Bug Report, and Screenshots.",
    submissionType: "file",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 3,
    title: "Bug Tracking Project",
    description: "Build a small bug tracking workflow for a chosen app and track 10+ bugs end-to-end.",
    instructions: "Choose an app. Identify and report 10+ bugs. Track them through Open/Assigned/Fixed/Verified using a tracker (Trello/Sheets). Include severity and priority. Submit Test Cases PDF, Bug Report, and Screenshots.",
    submissionType: "file",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 4,
    title: "Performance Testing Report",
    description: "Run performance tests on a public web app and produce a report with recommendations.",
    instructions: "Run performance tests (Lighthouse, WebPageTest) on a public app. Capture load time, FCP, LCP, CLS, and 3G/4G behavior. Document bottlenecks and 5 prioritized recommendations. Submit Test Cases PDF, Bug Report, and Screenshots.",
    submissionType: "file",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 5,
    title: "Quality Assurance Project",
    description: "Run an end-to-end QA cycle for a chosen small app and produce a release report.",
    instructions: "Pick a small app or your own project. Plan a full QA cycle: test plan, test cases, execution, bug reporting, regression, and a release readiness report. Submit Test Cases PDF, Bug Report, and Screenshots.",
    submissionType: "file",
    dueInDays: 14,
  }),
];

const cyberSecurityTasks = [
  mkTask({
    taskNumber: 1,
    title: "Password Security Analysis",
    description: "Analyze password strength practices and document findings and recommendations.",
    instructions: "Research password security: hashing, salting, MFA, common attack vectors, and best practices. Build a small demo (hash a list of weak passwords) and document findings. Submit an Audit Report PDF, a Research Document, and Screenshots.",
    submissionType: "file",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 2,
    title: "SSL Certificate Audit",
    description: "Audit SSL/TLS certificates of 5+ public websites and document findings.",
    instructions: "Pick 5+ public websites. Audit their SSL/TLS certificates (issuer, validity, grade on SSL Labs). Document strengths, weaknesses, and recommendations. Submit an Audit Report PDF, a Research Document, and Screenshots.",
    submissionType: "file",
    dueInDays: 7,
  }),
  mkTask({
    taskNumber: 3,
    title: "Phishing Awareness Research",
    description: "Research phishing techniques and build a phishing awareness material set.",
    instructions: "Research common phishing techniques. Build an awareness pack: a short guide, 5 example phishing emails (annotated), and a checklist for users. Submit an Audit Report PDF, a Research Document, and Screenshots.",
    submissionType: "file",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 4,
    title: "Website Security Assessment",
    description: "Perform a basic website security assessment and document vulnerabilities.",
    instructions: "Pick a public website (with permission, or use a deliberately vulnerable demo site). Run a basic security assessment (headers, cookies, exposed endpoints, SQLi/XSS quick checks) and document findings. Submit an Audit Report PDF, a Research Document, and Screenshots.",
    submissionType: "file",
    dueInDays: 10,
  }),
  mkTask({
    taskNumber: 5,
    title: "Cyber Security Report",
    description: "Compile a comprehensive cyber security report with findings and recommendations.",
    instructions: "Compile a comprehensive cyber security report: executive summary, methodology, findings (from prior tasks), prioritized recommendations, and an action plan. Submit an Audit Report PDF, a Research Document, and Screenshots.",
    submissionType: "file",
    dueInDays: 14,
  }),
];

export const programs = [
  {
    title: "Web Development Internship",
    domain: "Web Development",
    duration: "1 Month",
    stipend: "Unpaid",
    description:
      "Build five real-world web projects — portfolio, restaurant, e-commerce landing, college event, and company business sites — using HTML, CSS, and JavaScript.",
    skills: ["HTML5", "CSS3", "JavaScript", "Responsive Design", "Git", "Deployment"],
    coverImage: "",
    tasks: webDevTasks,
  },
  {
    title: "Full Stack Development Internship",
    domain: "Full Stack Development",
    duration: "2 Months",
    stipend: "Unpaid",
    description:
      "Build production-style full stack applications — student management, task management, employee management, online course platform, and e-commerce — across five mentor-reviewed projects.",
    skills: ["React", "Node.js", "Express", "MongoDB", "REST APIs", "Authentication"],
    coverImage: "",
    tasks: fullStackTasks,
  },
  {
    title: "MERN Stack Development Internship",
    domain: "MERN Stack",
    duration: "2 Months",
    stipend: "Unpaid",
    description:
      "Ship five MERN applications — task manager, expense tracker, job portal, online learning platform, and e-commerce MERN store — with deployable demos and GitHub submissions.",
    skills: ["MongoDB", "Express", "React", "Node.js", "JWT", "Deployment"],
    coverImage: "",
    tasks: mernTasks,
  },
  {
    title: "UI/UX Design Internship",
    domain: "UI/UX Design",
    duration: "2 Months",
    stipend: "Unpaid",
    description:
      "Design five complete product UIs — food delivery, e-commerce, banking, travel booking, and a company dashboard — in Figma with prototypes and a design system.",
    skills: ["Figma", "UI Design", "UX Research", "Prototyping", "Design Systems"],
    coverImage: "",
    tasks: uiuxTasks,
  },
  {
    title: "Digital Marketing Internship",
    domain: "Digital Marketing",
    duration: "2 Months",
    stipend: "Unpaid",
    description:
      "Plan and execute five digital marketing projects — social media, Instagram growth, Facebook Ads, brand promotion, and lead generation — with full campaign reports.",
    skills: ["Social Media", "Content Strategy", "Facebook Ads", "Instagram", "Analytics"],
    coverImage: "",
    tasks: digitalMarketingTasks,
  },
  {
    title: "SEO Internship",
    domain: "SEO",
    duration: "1 Month",
    stipend: "Unpaid",
    description:
      "Run real SEO work — audits, keyword research, on-page optimization, competitor analysis, and performance reporting — across five guided projects.",
    skills: ["SEO Audit", "Keyword Research", "On-Page SEO", "Analytics", "Reporting"],
    coverImage: "",
    tasks: seoTasks,
  },
  {
    title: "Graphic Design Internship",
    domain: "Graphic Design",
    duration: "2 Months",
    stipend: "Unpaid",
    description:
      "Build a graphic design portfolio across five projects — company logo, social media poster pack, brochure, event banners, and a complete brand identity kit.",
    skills: ["Logo Design", "Branding", "Print Design", "Social Media Creatives", "Adobe / Figma"],
    coverImage: "",
    tasks: graphicDesignTasks,
  },
  {
    title: "Content Writing Internship",
    domain: "Content Writing",
    duration: "2 Months",
    stipend: "Unpaid",
    description:
      "Write five high-quality content pieces — SEO blogs, website content, product descriptions, a social media content calendar, and a content portfolio.",
    skills: ["SEO Writing", "Web Copy", "Product Descriptions", "Editing", "Research"],
    coverImage: "",
    tasks: contentWritingTasks,
  },
  {
    title: "E-Commerce Management Internship",
    domain: "E-Commerce Management",
    duration: "2 Months",
    stipend: "Unpaid",
    description:
      "Manage an end-to-end e-commerce workflow across five projects — product listings, optimization, inventory tracking, sales analysis, and store operations.",
    skills: ["Product Listing", "Inventory", "Sales Analysis", "Store Management", "Excel"],
    coverImage: "",
    tasks: ecommerceMgmtTasks,
  },
  {
    title: "AI & Prompt Engineering Internship",
    domain: "AI & Prompt Engineering",
    duration: "2 Months",
    stipend: "Unpaid",
    description:
      "Build five AI prompt engineering projects — a prompt library, content generator workflow, support chatbot prompts, AI marketing automation, and a real business AI solution.",
    skills: ["Prompt Engineering", "ChatGPT / LLMs", "AI Tools", "Automation", "Workflow Design"],
    coverImage: "",
    tasks: aiPromptTasks,
  },
  {
    title: "React.js Development Internship",
    domain: "React.js",
    duration: "2 Months",
    stipend: "Unpaid",
    description:
      "Build five React applications — weather, movie search, expense tracker, admin dashboard, and an e-commerce storefront — with deployable demos.",
    skills: ["React.js", "Vite", "Tailwind CSS", "React Router", "APIs", "Deployment"],
    coverImage: "",
    tasks: reactTasks,
  },
  {
    title: "Data Analytics Internship",
    domain: "Data Analytics",
    duration: "2 Months",
    stipend: "Unpaid",
    description:
      "Analyze data across five projects — sales dashboard, customer analysis, market trends, data visualizations, and a business insights dashboard — using Excel and Power BI.",
    skills: ["Excel", "Power BI", "Data Analysis", "Visualization", "Reporting"],
    coverImage: "",
    tasks: dataAnalyticsTasks,
  },
  {
    title: "Video Editing Internship",
    domain: "Video Editing",
    duration: "2 Months",
    stipend: "Unpaid",
    description:
      "Edit five video projects — Instagram reel, YouTube video, promotional video, motion graphics, and a brand advertisement — with full sound design and color work.",
    skills: ["Premiere Pro / DaVinci", "After Effects", "Color Grading", "Sound Design", "Storytelling"],
    coverImage: "",
    tasks: videoEditingTasks,
  },
  {
    title: "Software Testing Internship",
    domain: "Software Testing",
    duration: "2 Months",
    stipend: "Unpaid",
    description:
      "Run five software testing projects — website testing, mobile app testing, bug tracking, performance testing, and a complete QA cycle — with test cases and bug reports.",
    skills: ["Test Cases", "Bug Reporting", "Manual Testing", "Performance Testing", "QA Process"],
    coverImage: "",
    tasks: softwareTestingTasks,
  },
  {
    title: "Cyber Security Internship",
    domain: "Cyber Security",
    duration: "2 Months",
    stipend: "Unpaid",
    description:
      "Work on five cyber security projects — password security, SSL audit, phishing awareness, website security assessment, and a full cyber security report.",
    skills: ["Cyber Security Basics", "SSL/TLS", "Phishing", "Web Security", "Reporting"],
    coverImage: "",
    tasks: cyberSecurityTasks,
  },
];
